### ISSUE TITLE
Running the model

### ISSUE THREAD

**Issue by agdt008** [360CVGroup/Inner-Adaptor-Architecture#1]
Hi, thanks you for sharing your work. I tried to run. But facing error described below:
OSError: qihoo360/iaa-14-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

I downloaded locally from github following the install steps. Could you please share the checkpoint?

Thank you.

**Comment by binwang777** [comment]
We have updated the name of the model in the readme to qihoo360/Inner-Adaptor-Architecture, the model has been uploaded to the huggingface community, you can download it to use locally or pull it automatically.

**Comment by agdt008** [comment]
Thank you!
