### ISSUE TITLE
Inference on text-only tasks

### ISSUE THREAD

**Issue by viyjy** [360CVGroup/Inner-Adaptor-Architecture#2]
Thanks for sharing this interesting work.
I was wondering how do you do the inference on text-only tasks such as MMLU? Do you just use Llama3?
If so, this work actually keeps two models, one is Llama3 for text-only tasks, and the other one is IAA for MM tasks. 
In this case, what's the benefit of this work compared to LLaVA-Llama3? We can also use Llama3 for text-only tasks, and use LLaVA-Llama3 for MM tasks.

**Comment by yuxie11** [comment]
Thank you for your attention. We have found in practice that the combination of llama3 and llava-llama3 requires two language models, whereas we only need one large language model in the deployment, which will be advantageous in terms of GPU memory. At the same time, compared to llava-llama3, IAA performs better on multimodal tasks using the same training data. The advantage of this approach will be more obvious when actually extending to more functions or more modalities.

> Thanks for sharing this interesting work. I was wondering how do you do the inference on text-only tasks such as MMLU? Do you just use Llama3? If so, this work actually keeps two models, one is Llama3 for text-only tasks, and the other one is IAA for MM tasks. In this case, what's the benefit of this work compared to LLaVA-Llama3? We can also use Llama3 for text-only tasks, and use LLaVA-Llama3 for MM tasks.
